version: "3.9"

networks:
  web:
    name: nginxproxy
    external: true

volumes:
  vaultwarden-data:

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - vaultwarden-data:/data
    networks:
      - web
