version: '3.9'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nextcloud
    networks:
      - nginxproxy

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nginxproxy

        #collabora:
        #  image: collabora/code
        #  restart: always
        #  environment:
        #    - domain=
        #    - extra_params=--o:ssl.enable=false
        #    - username=
        #    - pasword=
        #    - VIRTUAL_HOST=
        #    - LETSENCRYPT_HOST=
        #  cap_add:
        #    - MKNOD
        #  networks:
        #    - nginxproxy
        #

  app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=${VIRTUAL_HOST}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - APACHE_DISABLE_REWRITE_IP=1
      - OVERWRITEHOST=${VIRTUAL_HOST}
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    networks:
      - nginxproxy
    depends_on:
      #- collabora
      - db
      - redis

networks:
  nginxproxy:
    name: nginxproxy
    external: true
