version: "3.9"

networks:
  web:
    name: nginxproxy
    external: true

services:
  website:
    image: nginx:1.24.0-alpine
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    volumes:
      - ./src:/usr/share/nginx/html:ro
    networks:
      - web
